# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - g++ 
sudo: required
script:
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - make all clean  
  - sbt clean coverage test
  
after_success: "sbt coveralls"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
